// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: multirpcProto.proto

public final class MultiRPCProto {
  private MultiRPCProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface MultiRPCReqOrBuilder extends
      // @@protoc_insertion_point(interface_extends:MultiRPCReq)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required uint32 reqID = 1;</code>
     */
    boolean hasReqID();
    /**
     * <code>required uint32 reqID = 1;</code>
     */
    int getReqID();

    /**
     * <code>required string serviceName = 2;</code>
     */
    boolean hasServiceName();
    /**
     * <code>required string serviceName = 2;</code>
     */
    java.lang.String getServiceName();
    /**
     * <code>required string serviceName = 2;</code>
     */
    com.google.protobuf.ByteString
        getServiceNameBytes();

    /**
     * <code>required uint32 methodID = 3;</code>
     */
    boolean hasMethodID();
    /**
     * <code>required uint32 methodID = 3;</code>
     */
    int getMethodID();

    /**
     * <code>required bytes args = 4;</code>
     */
    boolean hasArgs();
    /**
     * <code>required bytes args = 4;</code>
     */
    com.google.protobuf.ByteString getArgs();
  }
  /**
   * Protobuf type {@code MultiRPCReq}
   */
  public  static final class MultiRPCReq extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:MultiRPCReq)
      MultiRPCReqOrBuilder {
    // Use MultiRPCReq.newBuilder() to construct.
    private MultiRPCReq(com.google.protobuf.GeneratedMessage.Builder builder) {
      super(builder);
    }
    private MultiRPCReq() {
      reqID_ = 0;
      serviceName_ = "";
      methodID_ = 0;
      args_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MultiRPCReq(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              reqID_ = input.readUInt32();
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              serviceName_ = bs;
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              methodID_ = input.readUInt32();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              args_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(
            new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this));
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return MultiRPCProto.internal_static_MultiRPCReq_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return MultiRPCProto.internal_static_MultiRPCReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              MultiRPCProto.MultiRPCReq.class, MultiRPCProto.MultiRPCReq.Builder.class);
    }

    private int bitField0_;
    public static final int REQID_FIELD_NUMBER = 1;
    private int reqID_;
    /**
     * <code>required uint32 reqID = 1;</code>
     */
    public boolean hasReqID() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required uint32 reqID = 1;</code>
     */
    public int getReqID() {
      return reqID_;
    }

    public static final int SERVICENAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object serviceName_;
    /**
     * <code>required string serviceName = 2;</code>
     */
    public boolean hasServiceName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string serviceName = 2;</code>
     */
    public java.lang.String getServiceName() {
      java.lang.Object ref = serviceName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          serviceName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string serviceName = 2;</code>
     */
    public com.google.protobuf.ByteString
        getServiceNameBytes() {
      java.lang.Object ref = serviceName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        serviceName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int METHODID_FIELD_NUMBER = 3;
    private int methodID_;
    /**
     * <code>required uint32 methodID = 3;</code>
     */
    public boolean hasMethodID() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required uint32 methodID = 3;</code>
     */
    public int getMethodID() {
      return methodID_;
    }

    public static final int ARGS_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString args_;
    /**
     * <code>required bytes args = 4;</code>
     */
    public boolean hasArgs() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required bytes args = 4;</code>
     */
    public com.google.protobuf.ByteString getArgs() {
      return args_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasReqID()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasServiceName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMethodID()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasArgs()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt32(1, reqID_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getServiceNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeUInt32(3, methodID_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, args_);
      }
      unknownFields.writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, reqID_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getServiceNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(3, methodID_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, args_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static MultiRPCProto.MultiRPCReq parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MultiRPCProto.MultiRPCReq parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MultiRPCProto.MultiRPCReq parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MultiRPCProto.MultiRPCReq parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MultiRPCProto.MultiRPCReq parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static MultiRPCProto.MultiRPCReq parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static MultiRPCProto.MultiRPCReq parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static MultiRPCProto.MultiRPCReq parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static MultiRPCProto.MultiRPCReq parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static MultiRPCProto.MultiRPCReq parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(MultiRPCProto.MultiRPCReq prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code MultiRPCReq}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:MultiRPCReq)
        MultiRPCProto.MultiRPCReqOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return MultiRPCProto.internal_static_MultiRPCReq_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return MultiRPCProto.internal_static_MultiRPCReq_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                MultiRPCProto.MultiRPCReq.class, MultiRPCProto.MultiRPCReq.Builder.class);
      }

      // Construct using MultiRPCProto.MultiRPCReq.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        reqID_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        serviceName_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        methodID_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        args_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return MultiRPCProto.internal_static_MultiRPCReq_descriptor;
      }

      public MultiRPCProto.MultiRPCReq getDefaultInstanceForType() {
        return MultiRPCProto.MultiRPCReq.getDefaultInstance();
      }

      public MultiRPCProto.MultiRPCReq build() {
        MultiRPCProto.MultiRPCReq result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public MultiRPCProto.MultiRPCReq buildPartial() {
        MultiRPCProto.MultiRPCReq result = new MultiRPCProto.MultiRPCReq(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.reqID_ = reqID_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.serviceName_ = serviceName_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.methodID_ = methodID_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.args_ = args_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof MultiRPCProto.MultiRPCReq) {
          return mergeFrom((MultiRPCProto.MultiRPCReq)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(MultiRPCProto.MultiRPCReq other) {
        if (other == MultiRPCProto.MultiRPCReq.getDefaultInstance()) return this;
        if (other.hasReqID()) {
          setReqID(other.getReqID());
        }
        if (other.hasServiceName()) {
          bitField0_ |= 0x00000002;
          serviceName_ = other.serviceName_;
          onChanged();
        }
        if (other.hasMethodID()) {
          setMethodID(other.getMethodID());
        }
        if (other.hasArgs()) {
          setArgs(other.getArgs());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasReqID()) {
          return false;
        }
        if (!hasServiceName()) {
          return false;
        }
        if (!hasMethodID()) {
          return false;
        }
        if (!hasArgs()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        MultiRPCProto.MultiRPCReq parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (MultiRPCProto.MultiRPCReq) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int reqID_ ;
      /**
       * <code>required uint32 reqID = 1;</code>
       */
      public boolean hasReqID() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required uint32 reqID = 1;</code>
       */
      public int getReqID() {
        return reqID_;
      }
      /**
       * <code>required uint32 reqID = 1;</code>
       */
      public Builder setReqID(int value) {
        bitField0_ |= 0x00000001;
        reqID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint32 reqID = 1;</code>
       */
      public Builder clearReqID() {
        bitField0_ = (bitField0_ & ~0x00000001);
        reqID_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object serviceName_ = "";
      /**
       * <code>required string serviceName = 2;</code>
       */
      public boolean hasServiceName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string serviceName = 2;</code>
       */
      public java.lang.String getServiceName() {
        java.lang.Object ref = serviceName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            serviceName_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string serviceName = 2;</code>
       */
      public com.google.protobuf.ByteString
          getServiceNameBytes() {
        java.lang.Object ref = serviceName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          serviceName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string serviceName = 2;</code>
       */
      public Builder setServiceName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        serviceName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string serviceName = 2;</code>
       */
      public Builder clearServiceName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        serviceName_ = getDefaultInstance().getServiceName();
        onChanged();
        return this;
      }
      /**
       * <code>required string serviceName = 2;</code>
       */
      public Builder setServiceNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        serviceName_ = value;
        onChanged();
        return this;
      }

      private int methodID_ ;
      /**
       * <code>required uint32 methodID = 3;</code>
       */
      public boolean hasMethodID() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required uint32 methodID = 3;</code>
       */
      public int getMethodID() {
        return methodID_;
      }
      /**
       * <code>required uint32 methodID = 3;</code>
       */
      public Builder setMethodID(int value) {
        bitField0_ |= 0x00000004;
        methodID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint32 methodID = 3;</code>
       */
      public Builder clearMethodID() {
        bitField0_ = (bitField0_ & ~0x00000004);
        methodID_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString args_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes args = 4;</code>
       */
      public boolean hasArgs() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required bytes args = 4;</code>
       */
      public com.google.protobuf.ByteString getArgs() {
        return args_;
      }
      /**
       * <code>required bytes args = 4;</code>
       */
      public Builder setArgs(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        args_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes args = 4;</code>
       */
      public Builder clearArgs() {
        bitField0_ = (bitField0_ & ~0x00000008);
        args_ = getDefaultInstance().getArgs();
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:MultiRPCReq)
    }

    // @@protoc_insertion_point(class_scope:MultiRPCReq)
    private static final MultiRPCProto.MultiRPCReq DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new MultiRPCProto.MultiRPCReq();
    }

    public static MultiRPCProto.MultiRPCReq getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    public static final com.google.protobuf.Parser<MultiRPCReq> PARSER =
        new com.google.protobuf.AbstractParser<MultiRPCReq>() {
      public MultiRPCReq parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new MultiRPCReq(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<MultiRPCReq> getParserForType() {
      return PARSER;
    }

    public MultiRPCProto.MultiRPCReq getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface MultiRPCRespOrBuilder extends
      // @@protoc_insertion_point(interface_extends:MultiRPCResp)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required uint32 reqID = 1;</code>
     */
    boolean hasReqID();
    /**
     * <code>required uint32 reqID = 1;</code>
     */
    int getReqID();

    /**
     * <code>required bytes results = 2;</code>
     */
    boolean hasResults();
    /**
     * <code>required bytes results = 2;</code>
     */
    com.google.protobuf.ByteString getResults();
  }
  /**
   * Protobuf type {@code MultiRPCResp}
   */
  public  static final class MultiRPCResp extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:MultiRPCResp)
      MultiRPCRespOrBuilder {
    // Use MultiRPCResp.newBuilder() to construct.
    private MultiRPCResp(com.google.protobuf.GeneratedMessage.Builder builder) {
      super(builder);
    }
    private MultiRPCResp() {
      reqID_ = 0;
      results_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MultiRPCResp(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              reqID_ = input.readUInt32();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              results_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(
            new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this));
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return MultiRPCProto.internal_static_MultiRPCResp_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return MultiRPCProto.internal_static_MultiRPCResp_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              MultiRPCProto.MultiRPCResp.class, MultiRPCProto.MultiRPCResp.Builder.class);
    }

    private int bitField0_;
    public static final int REQID_FIELD_NUMBER = 1;
    private int reqID_;
    /**
     * <code>required uint32 reqID = 1;</code>
     */
    public boolean hasReqID() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required uint32 reqID = 1;</code>
     */
    public int getReqID() {
      return reqID_;
    }

    public static final int RESULTS_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString results_;
    /**
     * <code>required bytes results = 2;</code>
     */
    public boolean hasResults() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required bytes results = 2;</code>
     */
    public com.google.protobuf.ByteString getResults() {
      return results_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasReqID()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasResults()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt32(1, reqID_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, results_);
      }
      unknownFields.writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, reqID_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, results_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static MultiRPCProto.MultiRPCResp parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MultiRPCProto.MultiRPCResp parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MultiRPCProto.MultiRPCResp parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MultiRPCProto.MultiRPCResp parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MultiRPCProto.MultiRPCResp parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static MultiRPCProto.MultiRPCResp parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static MultiRPCProto.MultiRPCResp parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static MultiRPCProto.MultiRPCResp parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static MultiRPCProto.MultiRPCResp parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static MultiRPCProto.MultiRPCResp parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(MultiRPCProto.MultiRPCResp prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code MultiRPCResp}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:MultiRPCResp)
        MultiRPCProto.MultiRPCRespOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return MultiRPCProto.internal_static_MultiRPCResp_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return MultiRPCProto.internal_static_MultiRPCResp_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                MultiRPCProto.MultiRPCResp.class, MultiRPCProto.MultiRPCResp.Builder.class);
      }

      // Construct using MultiRPCProto.MultiRPCResp.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        reqID_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        results_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return MultiRPCProto.internal_static_MultiRPCResp_descriptor;
      }

      public MultiRPCProto.MultiRPCResp getDefaultInstanceForType() {
        return MultiRPCProto.MultiRPCResp.getDefaultInstance();
      }

      public MultiRPCProto.MultiRPCResp build() {
        MultiRPCProto.MultiRPCResp result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public MultiRPCProto.MultiRPCResp buildPartial() {
        MultiRPCProto.MultiRPCResp result = new MultiRPCProto.MultiRPCResp(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.reqID_ = reqID_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.results_ = results_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof MultiRPCProto.MultiRPCResp) {
          return mergeFrom((MultiRPCProto.MultiRPCResp)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(MultiRPCProto.MultiRPCResp other) {
        if (other == MultiRPCProto.MultiRPCResp.getDefaultInstance()) return this;
        if (other.hasReqID()) {
          setReqID(other.getReqID());
        }
        if (other.hasResults()) {
          setResults(other.getResults());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasReqID()) {
          return false;
        }
        if (!hasResults()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        MultiRPCProto.MultiRPCResp parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (MultiRPCProto.MultiRPCResp) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int reqID_ ;
      /**
       * <code>required uint32 reqID = 1;</code>
       */
      public boolean hasReqID() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required uint32 reqID = 1;</code>
       */
      public int getReqID() {
        return reqID_;
      }
      /**
       * <code>required uint32 reqID = 1;</code>
       */
      public Builder setReqID(int value) {
        bitField0_ |= 0x00000001;
        reqID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint32 reqID = 1;</code>
       */
      public Builder clearReqID() {
        bitField0_ = (bitField0_ & ~0x00000001);
        reqID_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString results_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes results = 2;</code>
       */
      public boolean hasResults() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required bytes results = 2;</code>
       */
      public com.google.protobuf.ByteString getResults() {
        return results_;
      }
      /**
       * <code>required bytes results = 2;</code>
       */
      public Builder setResults(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        results_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes results = 2;</code>
       */
      public Builder clearResults() {
        bitField0_ = (bitField0_ & ~0x00000002);
        results_ = getDefaultInstance().getResults();
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:MultiRPCResp)
    }

    // @@protoc_insertion_point(class_scope:MultiRPCResp)
    private static final MultiRPCProto.MultiRPCResp DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new MultiRPCProto.MultiRPCResp();
    }

    public static MultiRPCProto.MultiRPCResp getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    public static final com.google.protobuf.Parser<MultiRPCResp> PARSER =
        new com.google.protobuf.AbstractParser<MultiRPCResp>() {
      public MultiRPCResp parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new MultiRPCResp(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<MultiRPCResp> getParserForType() {
      return PARSER;
    }

    public MultiRPCProto.MultiRPCResp getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_MultiRPCReq_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_MultiRPCReq_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_MultiRPCResp_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_MultiRPCResp_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023multirpcProto.proto\"Q\n\013MultiRPCReq\022\r\n\005" +
      "reqID\030\001 \002(\r\022\023\n\013serviceName\030\002 \002(\t\022\020\n\010meth" +
      "odID\030\003 \002(\r\022\014\n\004args\030\004 \002(\014\".\n\014MultiRPCResp" +
      "\022\r\n\005reqID\030\001 \002(\r\022\017\n\007results\030\002 \002(\014B\017B\rMult" +
      "iRPCProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_MultiRPCReq_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_MultiRPCReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_MultiRPCReq_descriptor,
        new java.lang.String[] { "ReqID", "ServiceName", "MethodID", "Args", });
    internal_static_MultiRPCResp_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_MultiRPCResp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_MultiRPCResp_descriptor,
        new java.lang.String[] { "ReqID", "Results", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
